### ISSUE TITLE
Plz help me

### ISSUE THREAD

**Issue by qzz13** [ZLaxtert/validator-paypalV1#1]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in C:\Users\aaaa\Desktop\validator-paypalV1-main\cli.php:46
Stack trace:
#0 {main}
  thrown in C:\Users\aaaa\Desktop\validator-paypalV1-main\cli.php on line 46

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\aaaa\Desktop\validator-paypalV1-main\cli.php:46
Stack trace:
#0 {main}
  thrown in C:\Users\aaaa\Desktop\validator-paypalV1-main\cli.php on line 46

**Comment by ZLaxtert** [comment]
Make sure you have installed PHP correctly
